
// Text pools for Practice mode - each level has 20 curated paragraphs
// Text is randomly selected on each practice session

const BASIC_TEXTS = [
    "The cat sat on the mat. The dog ran to the park. The sun is hot in the sky. I like to eat apples and bananas. It is a good day to be happy.",
    "The quick brown fox jumps over the lazy dog. Birds fly high in the blue sky. Fish swim deep in the ocean. Trees grow tall in the forest.",
    "My name is Alice and I like to read books. Today is a sunny day. I will go to the park with my friends. We will play games and have fun.",
    "Winter is cold and snow falls from the sky. Summer is warm and flowers bloom everywhere. Spring brings rain and new life. Fall has colorful leaves.",
    "I wake up early in the morning. I brush my teeth and wash my face. Then I eat a healthy breakfast. After that I go to school or work.",
    "The moon shines bright at night. Stars twinkle in the dark sky. The wind blows through the trees. Nature is beautiful and peaceful.",
    "My favorite color is blue like the ocean. I enjoy swimming in the pool. Water is cool and refreshing. I feel happy when I am near water.",
    "Books open new worlds for us to explore. Reading helps us learn many things. Libraries are quiet places full of knowledge. I love the smell of old books.",
    "My family is very important to me. We eat dinner together every night. We talk about our day and share stories. Love makes our home warm.",
    "Music makes me feel alive and happy. I like to dance when I hear a good song. Rhythm moves through my body. Art brings joy to life.",
    "The garden has many colorful flowers. Bees buzz around collecting nectar. Butterflies float gently in the breeze. Plants need water and sunlight to grow.",
    "My pet dog is my best friend. He wags his tail when he sees me. We go for walks every morning. Animals bring happiness to our lives.",
    "Rain falls softly on the roof. Puddles form on the ground. Children jump and splash in the water. Rainy days can be fun too.",
    "I like to cook food for my family. The kitchen smells wonderful when dinner is ready. We try new recipes every week. Cooking is a creative art.",
    "The beach is my favorite place to visit. Sand feels warm under my feet. Waves crash against the shore. Seagulls call out as they fly above.",
    "Learning new things makes me excited. Every day brings new opportunities. I ask questions when I am curious. Knowledge helps me grow as a person.",
    "Friends make life more enjoyable. We laugh and talk for hours. True friends support each other always. Friendship is a precious gift we share.",
    "The city is busy with people and cars. Buildings stand tall reaching for the sky. Lights shine bright when night falls. Urban life moves fast.",
    "My dream is to travel around the world. I want to see new places and meet new people. Different cultures teach us many lessons. Adventure awaits those who seek it.",
    "Exercise keeps our body strong and healthy. Running makes my heart beat faster. Fresh air fills my lungs. Taking care of ourselves is very important.",
    "Computers help us do many things faster and easier. We use them for writing, drawing, and playing games. The internet connects computers all around the world. Learning to use computers is a useful skill for everyone.",
    "Websites are like pages in a book that we can visit on the internet. They have text, pictures, and videos to share information. People create websites to teach, sell things, or share their ideas. Anyone can learn to make a simple website.",
    "Apps are programs that run on our phones and computers. Some apps help us stay organized with calendars and lists. Other apps let us chat with friends or watch videos. Developers write code to create new apps every day.",
    "Passwords keep our accounts safe from other people. We should use different passwords for different websites. Strong passwords have letters, numbers, and special symbols. Remembering passwords can be hard but it protects our information.",
    "Email lets us send messages to anyone in the world instantly. We can attach files like photos or documents to our emails. Checking email regularly helps us stay connected with work and friends. Writing clear emails is an important communication skill."
];

const INTERMEDIATE_TEXTS = [
    "Programming is the process of creating a set of instructions that tell a computer how to perform a task. JavaScript is a popular language for web development. It enables interactive web pages and is an essential part of modern applications.",
    "Artificial intelligence is transforming the way we live and work. Machine learning algorithms can analyze vast amounts of data to find patterns. These technologies are being applied in healthcare, finance, and many other industries to solve complex problems.",
    "Climate change is one of the most pressing issues of our time. Rising temperatures are causing ice caps to melt and sea levels to rise. Scientists around the world are working to develop sustainable solutions and reduce carbon emissions.",
    "Communication skills are essential in both personal and professional settings. Active listening helps us understand others better. Clear expression of ideas builds trust and prevents misunderstandings. Body language often speaks louder than words.",
    "The human brain is incredibly complex and fascinating. Neurons transmit information through electrical and chemical signals. Memory formation involves multiple regions working together. Research continues to unlock the mysteries of consciousness.",
    "Entrepreneurship requires creativity, persistence, and strategic thinking. Successful businesses identify problems and provide valuable solutions. Risk management and financial planning are crucial for long-term sustainability. Innovation drives progress in competitive markets.",
    "Photography captures moments that would otherwise be lost to time. Composition, lighting, and timing combine to create compelling images. Digital technology has made photography more accessible than ever before. Every photograph tells a unique story.",
    "Healthy eating habits contribute significantly to overall well-being. Balanced nutrition provides energy and supports bodily functions. Fresh fruits and vegetables contain essential vitamins and minerals. Moderation is key to maintaining a healthy lifestyle.",
    "Space exploration expands our understanding of the universe. Satellites orbiting Earth provide crucial data for weather forecasting and communication. Future missions aim to establish human presence on other planets. The cosmos holds infinite mysteries waiting to be discovered.",
    "Education is the foundation of personal and societal development. Critical thinking skills enable us to analyze information effectively. Teachers inspire students to reach their full potential. Lifelong learning keeps our minds sharp and adaptable.",
    "Music theory explains the principles that govern musical composition. Rhythm, melody, and harmony work together to create emotional responses. Different cultures have developed unique musical traditions over centuries. Practice and dedication are essential for mastering any instrument.",
    "Architecture blends art and engineering to create functional spaces. Sustainable design considers environmental impact and energy efficiency. Historic buildings tell stories of past civilizations and their values. Modern architecture continues to push boundaries of what is possible.",
    "Psychology studies the mind and behavior of individuals and groups. Cognitive processes influence how we perceive and interact with the world. Understanding mental health is crucial for overall wellness. Therapy and counseling provide support during difficult times.",
    "Financial literacy empowers people to make informed economic decisions. Budgeting helps track income and expenses effectively. Investments can grow wealth over time through compound interest. Planning for retirement ensures security in later years.",
    "Literature reflects the values, struggles, and dreams of humanity. Great writers craft stories that resonate across generations and cultures. Poetry condenses profound meaning into carefully chosen words. Reading expands our empathy and imagination.",
    "Environmental conservation protects biodiversity for future generations. Ecosystems maintain delicate balances that support all life. Pollution threatens air, water, and soil quality worldwide. Individual actions collectively make a significant impact.",
    "Digital security is increasingly important in our connected world. Strong passwords and encryption protect sensitive information. Cyber threats evolve constantly requiring vigilant defense strategies. Privacy concerns must be balanced with convenience.",
    "Scientific method provides a systematic approach to understanding nature. Hypothesis testing through controlled experiments yields reliable results. Peer review ensures quality and accuracy of research findings. Discovery builds upon previous knowledge incrementally.",
    "Effective leadership inspires teams to achieve common goals. Delegation empowers others to develop their skills and contribute meaningfully. Ethical decision-making builds trust and credibility. Great leaders adapt their style to different situations.",
    "Transportation systems connect people and goods across vast distances. Innovation in mobility aims to reduce environmental impact and increase efficiency. Urban planning must balance public transit with private vehicle needs. The future may bring autonomous vehicles and hyperloop technology.",
    "Cloud computing allows users to access data and applications over the internet instead of storing everything locally. Major providers like Amazon Web Services, Microsoft Azure, and Google Cloud offer scalable infrastructure. This technology enables businesses to reduce hardware costs and improve flexibility. Understanding cloud services is becoming essential for modern IT professionals.",
    "Version control systems like Git help developers track changes in their code over time. Teams can collaborate on projects without overwriting each other's work. Branching allows developers to experiment with new features safely. Platforms like GitHub and GitLab provide hosting and collaboration tools for software projects.",
    "Application Programming Interfaces or APIs enable different software systems to communicate with each other. RESTful APIs have become the standard for web services. Developers use APIs to integrate third-party services like payment processing or map data. Good API design makes software more modular and easier to maintain.",
    "Databases organize and store large amounts of information efficiently. SQL databases use structured tables with relationships between data. NoSQL databases offer more flexibility for handling unstructured data. Choosing the right database depends on the specific needs of each application.",
    "Responsive web design ensures websites work well on devices of all sizes from phones to desktop computers. CSS frameworks like Bootstrap provide pre-built components for faster development. Mobile-first design considers smaller screens as the primary use case. Testing across multiple devices is crucial for good user experience.",
    "Agile methodology breaks software development into short iterative cycles called sprints. Daily standup meetings keep team members aligned on progress and blockers. Continuous feedback from users helps prioritize the most valuable features. Agile practices have become the industry standard for many development teams.",
    "DevOps combines software development and IT operations to improve collaboration and automation. Continuous integration and deployment pipelines enable faster release cycles. Infrastructure as code allows teams to manage servers using version-controlled configuration files. These practices reduce manual errors and speed up delivery of new features.",
    "Open source software is developed collaboratively and made freely available to the public. Projects like Linux, Python, and React power much of the modern internet. Contributors from around the world improve the code and fix bugs. Companies often contribute to open source while also using it in their commercial products."
];

const ADVANCED_TEXTS = [
    "The internet has fundamentally changed how we communicate and access information in our daily lives. Social media platforms connect billions of people across the globe, enabling instant sharing of ideas and experiences. However, this connectivity also brings challenges such as information overload and the spread of misinformation. Learning to navigate the digital world responsibly is increasingly important for everyone.",
    "Modern cities face numerous challenges as populations continue to grow and urban areas expand. Traffic congestion, air pollution, and housing shortages require innovative solutions and careful planning. Smart city technologies use data and sensors to improve efficiency in transportation, energy use, and public services. Sustainable urban development aims to create livable spaces that balance growth with environmental protection.",
    "The global economy has become increasingly interconnected through international trade and investment. Companies operate across borders, creating complex supply chains that span multiple countries. Economic decisions in one region can have ripple effects around the world. Understanding these connections helps us make sense of market trends and their impact on our daily lives.",
    "Renewable energy sources like solar and wind power are becoming more affordable and widespread. These technologies offer alternatives to fossil fuels and help reduce greenhouse gas emissions. Battery storage systems are improving, making renewable energy more reliable even when the sun is not shining or the wind is not blowing. The transition to clean energy represents one of the most significant infrastructure changes of our time.",
    "The healthcare industry is being transformed by new technologies and approaches to treatment. Electronic medical records allow doctors to access patient information quickly and coordinate care more effectively. Telemedicine enables remote consultations, making healthcare more accessible to people in rural areas. Advances in medical research continue to improve our understanding of diseases and develop new therapies.",
    "Online education has expanded access to learning opportunities for millions of people worldwide. Students can take courses from prestigious universities without leaving their homes. Interactive tools and multimedia content make learning more engaging and personalized. However, digital learning also requires self-discipline and reliable internet access, which are not available to everyone.",
    "Food production systems face the challenge of feeding a growing global population while minimizing environmental impact. Sustainable farming practices aim to protect soil health, conserve water, and reduce chemical use. Innovations in agriculture include precision farming, vertical gardens, and alternative protein sources. The choices we make about food consumption have far-reaching effects on both health and the environment.",
    "Cybersecurity has become a critical concern for individuals, businesses, and governments. Hackers and cybercriminals constantly develop new methods to steal data and disrupt systems. Protecting sensitive information requires multiple layers of defense and regular updates to security measures. As more aspects of our lives move online, understanding basic security practices becomes essential for everyone.",
    "The entertainment industry has undergone dramatic changes with the rise of streaming services and digital distribution. Traditional media companies are adapting to new consumption patterns and competition from technology firms. Content creators have more opportunities than ever to reach audiences directly without traditional gatekeepers. However, the abundance of choices can also make it harder for individual works to stand out.",
    "Work environments are evolving as remote and flexible arrangements become more common. Technology enables collaboration across distances, changing traditional office dynamics. Companies are rethinking workplace design and policies to support employee wellbeing and productivity. The future of work will likely involve a blend of in-person and remote elements tailored to different roles and preferences.",
    "Personal data has become valuable to companies seeking to understand consumer behavior and preferences. Every online action generates information that can be collected and analyzed. Privacy concerns arise when data is used in ways that individuals did not anticipate or approve. Regulations are emerging to give people more control over their personal information and how it is used.",
    "Manufacturing is being revolutionized by automation and advanced robotics. Factories are becoming smarter with machines that can adapt to different tasks and predict maintenance needs. Three-dimensional printing allows for rapid prototyping and customized production. These technological advances change the skills workers need and raise questions about job displacement and retraining.",
    "Personal finance management has been simplified by mobile apps and online tools that track spending and investments. However, financial literacy remains crucial for making informed decisions about saving, borrowing, and planning for the future. Understanding compound interest, diversification, and risk helps people build financial security. Economic uncertainty makes these skills even more valuable.",
    "Successful businesses today must be agile and responsive to rapidly changing market conditions. Customer expectations evolve quickly, driven by new technologies and competitive offerings. Companies invest heavily in research and development to stay ahead of trends. Building a strong company culture and attracting talented employees are as important as product innovation.",
    "Travel and tourism connect people with different cultures and create economic opportunities around the world. Sustainable tourism practices aim to minimize negative impacts on local communities and natural environments. Technology has made planning and booking trips easier while also enabling virtual experiences. The industry continues to adapt to changing preferences and global events that affect mobility.",
    "Scientific research relies on collaboration between specialists from various fields working together on complex problems. Peer review and reproducible results ensure the quality and reliability of findings. Funding for research comes from government agencies, private companies, and nonprofit organizations with different priorities. Communicating scientific discoveries to the public helps build support for continued investigation.",
    "The housing market reflects broader economic conditions and has significant effects on household wealth. First-time buyers face challenges with rising prices and limited inventory in many areas. Rental markets provide flexibility but may lack the stability and investment potential of homeownership. Understanding real estate trends helps people make one of the most important financial decisions they will face.",
    "Transportation networks determine how easily people and goods can move within and between cities. Public transit systems reduce traffic congestion and environmental impact but require substantial investment and coordination. Emerging technologies like electric and autonomous vehicles promise to reshape mobility in coming decades. Infrastructure decisions made today will influence urban development for generations.",
    "Social movements use digital tools to organize, spread awareness, and mobilize supporters around causes they care about. Hashtags and viral content can bring attention to issues that traditional media might overlook. However, online activism also faces challenges from polarization, misinformation, and the difficulty of translating digital engagement into lasting change. Effective movements combine online and offline strategies.",
    "Mental health awareness has increased significantly as people become more comfortable discussing emotional wellbeing. Therapy and counseling services are more accessible through online platforms and workplace benefits. Stress management techniques and mindfulness practices help people cope with the pressures of modern life. Reducing stigma around mental health issues encourages more people to seek help when they need it.",
    "Kubernetes orchestrates containerized applications across clusters of machines, automating deployment, scaling, and management. Containers package applications with their dependencies, ensuring consistency across development and production environments. Docker revolutionized how developers build and ship software by making containers accessible. Modern cloud-native architectures rely heavily on container orchestration for resilience and efficiency.",
    "Microservices architecture breaks applications into small, independently deployable services that communicate through APIs. This approach enables teams to develop, test, and deploy components separately without affecting the entire system. Service meshes like Istio provide traffic management, security, and observability for microservices. However, distributed systems introduce complexity in debugging, monitoring, and maintaining data consistency.",
    "Machine learning models require careful training on large datasets to recognize patterns and make predictions. Neural networks with multiple layers enable deep learning capabilities that power image recognition and natural language processing. Transfer learning allows developers to leverage pre-trained models for specific tasks with less data. The ethical implications of AI systems including bias, transparency, and accountability remain active areas of concern and research.",
    "Continuous integration and continuous deployment pipelines automate the process of testing and releasing software updates. Jenkins, GitLab CI, and GitHub Actions are popular tools for building these workflows. Automated testing catches bugs early while deployment automation reduces human error. Site reliability engineering practices ensure systems remain available and performant as they scale.",
    "Serverless computing abstracts infrastructure management allowing developers to focus purely on code. Functions execute in response to events and scale automatically based on demand. AWS Lambda, Azure Functions, and Google Cloud Functions charge only for actual computation time used. This model works well for event-driven architectures but may introduce latency and vendor lock-in challenges.",
    "GraphQL provides a more flexible alternative to REST APIs by allowing clients to request exactly the data they need. A single GraphQL endpoint can serve multiple client applications with different requirements. Type safety and introspection make GraphQL APIs self-documenting and easier to evolve. However, caching strategies and query optimization require different approaches than traditional REST endpoints.",
    "Infrastructure as code tools like Terraform and Ansible enable teams to provision and configure resources using declarative specifications. Version controlling infrastructure alongside application code improves reproducibility and audit trails. Immutable infrastructure principles treat servers as disposable rather than long-lived pets. These practices are fundamental to achieving reliable and repeatable deployments in cloud environments.",
    "Software security encompasses multiple layers from secure coding practices to network protection and access control. Common vulnerabilities like SQL injection and cross-site scripting can be prevented through input validation and parameterized queries. Security testing should be integrated throughout the development lifecycle rather than treated as an afterthought. Regular updates and patch management address newly discovered vulnerabilities in dependencies."
];

// Function to get random text for a given difficulty level
const getRandomText = (textArray) => {
    const randomIndex = Math.floor(Math.random() * textArray.length);
    return textArray[randomIndex];
};

export const DIFFICULTY_TEXTS = {
    basic: () => getRandomText(BASIC_TEXTS),
    intermediate: () => getRandomText(INTERMEDIATE_TEXTS),
    advanced: () => getRandomText(ADVANCED_TEXTS)
};
